services:
  db:
    image: postgres:latest
    container_name: shukai_chat_db
    restart: always
    environment:
      POSTGRES_USER: shukai_chat
      POSTGRES_PASSWORD: shukai_chat
      POSTGRES_DB: shukai_chat
    ports:
      - "5134:5432"
    volumes:
      - chat_data:/var/lib/postgresql/data

volumes:
  chat_data:
    driver: local