server:
  port: 0
  servlet:
    context-path: /api

spring:
  application:
    name: catalogue-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-group
      auto-offset-reset: earliest
    producer:
      retries: 3
      acks: all
  cloud:
    openfeign:
      client:
        config:
          feignName:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8861/eureka

