services:
  db:
    image: postgres:latest
    container_name: shukai_order_db
    restart: always
    environment:
      POSTGRES_USER: shukai_order
      POSTGRES_PASSWORD: shukai_order
      POSTGRES_DB: shukai_order
    ports:
      - "5135:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

volumes:
  order_data:
    driver: local