services:
  db:
    image: postgres:latest
    container_name: shukai_user_db
    restart: always
    environment:
      POSTGRES_USER: shukai_user
      POSTGRES_PASSWORD: shukai_user
      POSTGRES_DB: shukai_user
    ports:
      - "5133:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  user_data:
    driver: local